version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
    versioning-strategy: increase
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
