name: Publish
on:
  push:
    tags: ['*']

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Get tag
        uses: olegtarasov/get-tag@v2.1.3
        id: tagName

      - name: Build Electron App
        uses: heliomarpm/action-electron-builder@2.0.0
        env:
          MAIN_VITE_APP_VERSION: $GIT_TAG_NAME
          RENDERER_VITE_APP_VERSION: $GIT_TAG_NAME
          MAIN_VITE_API: ${{secrets.MAIN_VITE_API}}
          MAIN_VITE_TOKEN: ${{secrets.MAIN_VITE_TOKEN}}
          MAIN_VITE_BUGSNAG: ${{secrets.MAIN_VITE_BUGSNAG}}
          RENDERER_VITE_BUGSNAG: ${{secrets.RENDERER_VITE_BUGSNAG}}
          MAIN_VITE_NODE_ENV: production
          RENDERER_VITE_NODE_ENV: production
          APPLE_ID: ${{ secrets.APPLEID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLEIDPASS }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
        with:
          max_attempts: 3
          github_token: ${{ secrets.github_token }}
          release: true
